Project:
  type: object
  properties:
    id:
      type: string
      format: uuid
    title:
      type: string
      maxLength: 150
    slug:
      type: string
      maxLength: 160
    description:
      type: string
      nullable: true
    content:
      type: object
      nullable: true
      description: Estructura JSON de EditorJS
    repoUrl:
      type: string
      nullable: true
      maxLength: 255
    liveUrl:
      type: string
      nullable: true
      maxLength: 255
    areaId:
      type: string
      format: uuid
      nullable: true
    year:
      type: integer
      nullable: true
    isFeatured:
      type: boolean
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    area:
      $ref: '../stack/area.yaml#/StackArea'
    technologies:
      type: array
      items:
        $ref: '../stack/technology.yaml#/Technology'
    files:
      type: array
      items:
        type: object
        properties:
          fileId:
            type: string
            format: uuid
          order:
            type: integer
          file:
            $ref: './file.yaml#/File'

CreateProjectInput:
  type: object
  required: [title, slug]
  properties:
    title:
      type: string
      maxLength: 150
    slug:
      type: string
      maxLength: 160
    description:
      type: string
      nullable: true
    content:
      type: object
      nullable: true
    repoUrl:
      type: string
      nullable: true
    liveUrl:
      type: string
      nullable: true
    areaId:
      type: string
      format: uuid
      nullable: true
    year:
      type: integer
      nullable: true
    isFeatured:
      type: boolean
      default: false
    technologyIds:
      type: array
      items:
        type: string
        format: uuid

UpdateProjectInput:
  type: object
  properties:
    title:
      type: string
    slug:
      type: string
    description:
      type: string
    content:
      type: object
    repoUrl:
      type: string
    liveUrl:
      type: string
    areaId:
      type: string
      format: uuid
    year:
      type: integer
    isFeatured:
      type: boolean
    technologyIds:
      type: array
      items:
        type: string
        format: uuid